version: '3.1'
services:
    react:
        build:
            context: ./management-web-ui
            dockerfile: Dockerfile
        container_name: management-web-ui
        volumes:
            - './management-web-ui/src:/management-web-ui/src'
        #volumes:
        #  - '../frontend:/frontend'
        ports:
            - 3000:3000
        stdin_open: true