version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/node:19.0.0'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'cd ./management-web-ui && yarn install --ignore-engines && npm run build'
      - sonarcloud/scan
      
  test:
    docker:
      - image: 'cimg/node:19.0.0'
    steps:
          - checkout
          - run:
              name: Run e2e tests
              command: |
                cd ./management-web-ui
                yarn --ignore-engines
                yarn e2e

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0

workflows:
  main:
    jobs:
      - test
      - build:
          context: SonarCloud
          requires:
            - test
      - aws-ecr/build-and-push-image:
          path: ./management-web-ui/
          region: ${AWS_REGION}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - develop
      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     family: ${CIRCLE_PROJECT_REPONAME}-task
      #     cluster: ${CIRCLE_PROJECT_REPONAME}-cluster
      #     container-image-name-updates: 'container=${CIRCLE_PROJECT_REPONAME}-container,tag=67'