version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/node:19.0.0'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'cd ./management-web-ui && yarn install --ignore-engines && npm run build'
      - sonarcloud/scan
      
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: cd ./management-web-ui && yarn install --ignore-engines && npm run build
      - run: cd ./management-web-ui && npm run test

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  main:
    jobs:
      - test
      - build:
          context: SonarCloud
          requires:
            - test
      - aws-ecr/build-and-push-image:
          path: ./management-web-ui/
          region: ${AWS_REGION}
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - test